### ISSUE TITLE
some  advice!

### ISSUE THREAD

**Issue by AuguxAX** [LarsWalter/pointo-bot#11]
so i fixed google api issue changing (      range: `Current!A$2:C`,  by        range: `A$2:C`,
and     (    range: 'Current!A2:C', // Sheet data selector    by       range: 'A2:C',

**Comment by LarsWalter** [comment]
'Current' is the name of the page/sheet in the spreadsheet (bottom left). I should mentioned that in the readme. I won't be removing since the way i plan on making the reset command is by creating a new sheet, so the data isn't deleted, just moved.

**Comment by AuguxAX** [comment]
Ohh! ok

**Comment by LarsWalter** [comment]
It only works if the user already exists in the sheet, as in they've used a command to give themselves points before. I'll look to improve this, but I'm not sure I'll be able to.

**Comment by LarsWalter** [comment]
Closing in favour of #13 which is why your queries don't match any users.
