### ISSUE TITLE
Json file issue

### ISSUE THREAD

**Issue by AuguxAX** [LarsWalter/pointo-bot#2]
Successfully compiled 10 files with Babel.
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Users\user\Desktop\pointo-bot-master\dist\index.js:25:25
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by LarsWalter** [comment]
Also this is a very barebones repo, I didn't expect anyone else to run this thing, so things like checking if config files exist have been pretty lax and there might be bugs / not be very robust. If you have another discord bot you're running you can probably just grab whatever functionality you want from here and implement it in your own.

**Comment by AuguxAX** [comment]
ok, that is great

**Comment by LarsWalter** [comment]
I'll be adding both of those things. 👍 Give and take commands for admins and option to print the leaderboard instead of linking the actual sheet.

**Comment by AuguxAX** [comment]
Amazing!!! keep it up man
